package com.eljavatar.udistrital.ritmocardiaco.exceptions;

public enum MensajeErrorEnum {

    SYSTEM_ERROR,
    
    EXCEPTION_OBTENIENDO_LIST_ENTITY,
    EXCEPTION_INSERT_ENTITY,
    EXCEPTION_UPDATE_ENTITY,
    EXCEPTION_DELETE_ENTITY,
    EXCEPTION_FINDBYID_ENTITY,
    EXCEPTION_SELECT_COUNT_ENTITY,
    EXCEPTION_CONSTRAINT_ENTITY,
    
    EXCEPTION_SEARCH_USER_BY_USERNAME,
    
    EXCEPTION_INSERT_PERSONA,
    EXCEPTION_INSERT_HISTORICO_RITMO,
    
    EXCEPTION_SELECT_LIST_HISTORICO_RITMO;
	
}
